### ISSUE TITLE
2 colors for spin

### ISSUE THREAD

**Issue by ccartrec** [fgnass/spin.js#310] opened 2015-11-30 09:45 UTC
how make 2 colors for my spin?
![spin](https://cloud.githubusercontent.com/assets/4283143/11468368/fdf820d8-975f-11e5-8e7a-13d2fcc76762.png)
first - red
second - green

**Comment by theodorejb** [comment] 2017-11-06 17:18
spin.js does allow passing an array to the `color` option, but it ends up just alternating the colors on each line:

![multiple colors](https://user-images.githubusercontent.com/3053271/32454149-f94bb138-c2e3-11e7-9a68-4203ce4a2e8b.PNG)

The issue here is that spin.js relies on opacity, rather than a color for the spin effect.

**Comment by theodorejb** [comment] 2017-11-07 19:27
I think this may be a duplicate of issue #30.

**Closed** 2017-11-15 17:51 UTC
