### ISSUE TITLE
Spinner looks weird when centered on odd number parent container widths...

### ISSUE THREAD

**Issue by benmcmaster** [fgnass/spin.js#380] opened 2020-08-22 04:10 UTC
When I add the spinner to my site I noticed that half of the time it looks really weird on Chrome. Looks fine on Safari and Firefox.

It seems it looks weird when the parent container of spinner has a width with an odd number of pixels... 

Check out the weirdness: https://drive.google.com/file/d/13aGRQdhJ-d6pxOo1fZPl3sfwJijRcnWx/view?usp=sharing

Is this some sort of rounding error?

**Comment by theodorejb** [comment] 2020-08-26 16:28
@benmcmaster Can you share the code to reproduce? E.g. by forking this StackBlitz example: https://stackblitz.com/edit/spin-js-starter?file=index.ts

**Comment by theodorejb** [comment] 2024-07-22 14:04
Closing since I don't have a way to reproduce this.

**Closed by theodorejb** 2024-07-22 14:04 UTC
