### ISSUE TITLE
Updated NuGet Package

### ISSUE THREAD

**Issue by ddelella** [fgnass/spin.js#301] opened 2015-08-19 17:59 UTC
Any chance of getting the latest versions published to NuGet?  The last publicly release version is showing 2.0.1 but the website is on 2.3.2.  Thanks

**Comment by TimothyGu** [comment] 2015-08-19 19:04
Duplicate of #209. Do you know how to publish it on nuget? i.e. what are the commands for it? I don't really use windows that much these days so I'm kinda out-of-date on nuget…

**Closed by TimothyGu** 2015-08-19 19:04 UTC
